/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubesoop;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author Inside
 */
public class LoketOnline extends javax.swing.JFrame {

    tabelkonten tk = new tabelkonten();
    private Connection koneksi;
    int nopaket, paket1, paket2, pajak, harga, total, totalpajak;
    
    

    /**
     * Creates new form LoketOnline
     */
    public LoketOnline() {
        initComponents();
        KoneksiDatabase();
        setLocationRelativeTo(this);
        
       
    }
    
    public LoketOnline(String Nama, String ID, String Pesanan, String Biaya){
        initComponents();
        KoneksiDatabase();
        t_pembeli.setText(Nama);
        t_id.setText(ID);
        cmb_pembelian.setSelectedItem(Pesanan);
        t_total.setText(Biaya);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        t_pembeli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_pembelian = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        t_harga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmb_pembayaran = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_pajak = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_total = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        no_paket = new javax.swing.JRadioButton();
        paket_1 = new javax.swing.JRadioButton();
        paket_2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nama Pembeli             :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 124, -1));

        t_pembeli.setBackground(new java.awt.Color(102, 255, 0));
        getContentPane().add(t_pembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 100, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel3.setText("PEMBELIAN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setText("Pilih Pembelian            :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cmb_pembelian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "PULSA", "PLN", "PDAM", "WIFI" }));
        cmb_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_pembelianActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 99, -1));

        jLabel5.setText("Harga                       :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        t_harga.setBackground(new java.awt.Color(102, 255, 0));
        getContentPane().add(t_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 98, 30));

        jLabel6.setText("Pilih Pembayaran      :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        cmb_pembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", "DEBIT", "CASH" }));
        cmb_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_pembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(cmb_pembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 97, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 14)); // NOI18N
        jLabel7.setText("PEMBAYARAN");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, -1, -1));

        jLabel8.setText("PAJAK                       :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 435, -1, -1));

        t_pajak.setBackground(new java.awt.Color(102, 255, 0));
        getContentPane().add(t_pajak, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 435, 98, 30));

        jLabel9.setText("TOTAL                      :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 487, -1, -1));

        t_total.setBackground(new java.awt.Color(102, 255, 0));
        getContentPane().add(t_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 487, 98, 30));

        jLabel10.setText("Pilih Paket                  :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        buttonGroup1.add(no_paket);
        no_paket.setText("No Paket");
        no_paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_paketActionPerformed(evt);
            }
        });
        getContentPane().add(no_paket, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        buttonGroup1.add(paket_1);
        paket_1.setText("Paket 1");
        paket_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paket_1ActionPerformed(evt);
            }
        });
        getContentPane().add(paket_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        buttonGroup1.add(paket_2);
        paket_2.setText("Paket 2");
        paket_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paket_2ActionPerformed(evt);
            }
        });
        getContentPane().add(paket_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel11.setText("No.HP / ID                  :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        t_id.setBackground(new java.awt.Color(102, 255, 0));
        getContentPane().add(t_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 100, 30));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 725, 20));

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 725, 20));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubesoop/Webp.net-resizeimagvdfe.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 40, 40));

        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 80, -1));

        jButton2.setText("RESET");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 570, 120, -1));

        jButton4.setText("BAYAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 73, -1));

        jButton5.setText("UBAH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, 65, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("LOKET ONLINE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 730, 60));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 730, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 730, 10));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("%");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        jLabel14.setText("Rp.");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, -1, -1));

        jLabel15.setText("* Jika anda tidak membeli PAKET,");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, -1, 40));

        jLabel16.setText("biaya normal akan dikenakan Pajak.");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubesoop/bgremidi2.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmb_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_pembelianActionPerformed
        // TODO add your handling code here:
        if (cmb_pembelian.getSelectedItem().equals("PULSA")) {
            paket1 = 10000;
            paket2 = 20000;
            nopaket = 0;
        } else if (cmb_pembelian.getSelectedItem().equals("PLN")) {
            paket1 = 150000;
            paket2 = 300000;
            nopaket = 0;
        } else if (cmb_pembelian.getSelectedItem().equals("PDAM")) {
            paket1 = 50000;
            paket2 = 120000;
            nopaket = 0;
        } else if (cmb_pembelian.getSelectedItem().equals("WIFI")) {
            paket1 = 250000;
            paket2 = 450000;
            nopaket = 0;
        }
    }//GEN-LAST:event_cmb_pembelianActionPerformed

    private void no_paketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_paketActionPerformed
        // TODO add your handling code here:
        if (no_paket.isSelected()) {
            t_harga.setText(String.valueOf(nopaket));
            JOptionPane.showMessageDialog(null, "Mohon Masukkan " + "Nominal Harga yang ingin Anda Beli !", "HINT", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_no_paketActionPerformed

    private void paket_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paket_1ActionPerformed
        // TODO add your handling code here:
        if (paket_1.isSelected()) {
            t_harga.setText(String.valueOf(paket1));
        }
    }//GEN-LAST:event_paket_1ActionPerformed

    private void paket_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paket_2ActionPerformed
        // TODO add your handling code here:
        if (paket_2.isSelected()) {
            t_harga.setText(String.valueOf(paket2));
        }
    }//GEN-LAST:event_paket_2ActionPerformed

    private void cmb_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_pembayaranActionPerformed
        // TODO add your handling code here:
        //PULSA
        if (cmb_pembelian.getSelectedItem().equals("PULSA")) {
            if (no_paket.isSelected()) {
                pajak = 10;
                t_pajak.setText(String.valueOf(pajak));
            } else if (paket_1.isSelected()) {
                pajak = 0;
                t_pajak.setText(String.valueOf(pajak));
            } else if (paket_2.isSelected()) {
                pajak = 0;
                t_pajak.setText(String.valueOf(pajak));
            }
        } // PLN
        else if (cmb_pembelian.getSelectedItem().equals("PLN")) {
            if (no_paket.isSelected()) {
                pajak = 20;
                t_pajak.setText(String.valueOf(pajak));
            } else if (paket_1.isSelected()) {
                pajak = 0;
                t_pajak.setText(String.valueOf(pajak));
            } else if (paket_2.isSelected()) {
                pajak = 0;
                t_pajak.setText(String.valueOf(pajak));
            }
        } //PDAM
        else if (cmb_pembelian.getSelectedItem().equals("PDAM")) {
            if (no_paket.isSelected()) {
                pajak = 5;
                t_pajak.setText(String.valueOf(pajak));
            } else if (paket_1.isSelected()) {
                pajak = 0;
                t_pajak.setText(String.valueOf(pajak));
            } else if (paket_2.isSelected()) {
                pajak = 0;
                t_pajak.setText(String.valueOf(pajak));
            }
        } //WIFI
        else if (cmb_pembelian.getSelectedItem().equals("WIFI")) {
            if (no_paket.isSelected()) {
                pajak = 25;
                t_pajak.setText(String.valueOf(pajak));
            } else if (paket_1.isSelected()) {
                pajak = 0;
                t_pajak.setText(String.valueOf(pajak));
            } else if (paket_2.isSelected()) {
                pajak = 0;
                t_pajak.setText(String.valueOf(pajak));
            }
        }
    }//GEN-LAST:event_cmb_pembayaranActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        harga = Integer.parseInt(t_harga.getText());
        pajak = Integer.parseInt(t_pajak.getText());
        totalpajak = (pajak * harga) / 100;
        total = (harga + totalpajak);
        t_pajak.setVisible(true);
        t_pajak.setText(String.valueOf(totalpajak));
        t_total.setText(String.valueOf(total));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        t_pembeli.setText("");
        t_id.setText("");
        cmb_pembelian.setSelectedItem("PILIH");
        t_harga.setText("");
        buttonGroup1.clearSelection();
        cmb_pembayaran.setSelectedItem("PILIH");
        t_pajak.setText("");
        t_pajak.setText("");
        t_total.setText("");
        t_pembeli.requestFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int answer = JOptionPane.showConfirmDialog(null, "Anda yakin ingin keluar ? ", "Selesai", JOptionPane.OK_OPTION);
        if (answer == JOptionPane.OK_OPTION) {
            dispose();
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        String Nama = t_pembeli.getText();
        String ID = t_id.getText();
        String Pesanan = (String) cmb_pembelian.getSelectedItem();
        String Biaya = t_total.getText();
        //tabelkonten tk = new tabelkonten(Nama, Alamat, Pesanan, Biaya);
        //new tabelkonten(Nama, Alamat, Pesanan, Biaya).setVisible(true);
        if (t_pembeli.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Mohon Masukkan Data Untuk " + "Di Input", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                java.sql.Statement stat = koneksi.createStatement();
                ResultSet data = stat.executeQuery("SELECT * FROM orderan " + "WHERE Nama ='" + Nama + "'");
                if (data.next()) {
                    JOptionPane.showMessageDialog(null, "Nama Sudah Ada", "PERHATIAN", JOptionPane.WARNING_MESSAGE);
                    t_pembeli.requestFocus();
                } else {
                    String sql = "INSERT INTO orderan VALUES("
                            + "'" + Nama + "'"
                            + ",'" + ID + "'"
                            + ",'" + Pesanan + "'"
                            + ",'" + Biaya + "')";
                    //String sql = "INSERT INTO orderan VALUES(" + "'" + Nama + "'" + ",'" + Alamat + "'" + ",'" + Pesanan + "'" + ",'" + Biaya + "')";
                    stat.executeUpdate(sql);
                    t_pembeli.setText("");
                    t_id.setText("");
                    cmb_pembelian.setActionCommand("");
                    cmb_pembayaran.setActionCommand("");
                    t_total.setText("");
                    t_pembeli.requestFocus();
                    JOptionPane.showMessageDialog(null, "Data Berhasil di" + "Simpan", "SUKSES", JOptionPane.INFORMATION_MESSAGE);
//                    tk.TampilData();'
                    tk.show();
                    this.setVisible(false);
                }
                stat.close();
            } catch (HeadlessException | SQLException exc) {
                System.out.println("Terjadi Kesalahan :" + exc);
            }
        }


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null, "yakin ingin mengubah " + "data ini ?", "Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "Update orderan set ID='" + t_id.getText() + "',Pembelian='" + cmb_pembelian.getSelectedItem() + "',Biaya='" + t_total.getText() + "'where Nama='" + t_pembeli.getText().trim() + "'";
            if (t_pembeli.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Data masih kosong!", "Ubah Data", JOptionPane.WARNING_MESSAGE);
                t_pembeli.requestFocus();
            }else{
                try{
                    Statement stat = koneksi.createStatement();
                    stat.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah", "Ubah Data", JOptionPane.INFORMATION_MESSAGE);
                    stat.close();
                    t_pembeli.requestFocus();
                    tk.show();
                    this.setVisible(false);
                }catch (Exception exc){
                    System.out.println("Error :" + exc);
                }
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoketOnline.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoketOnline().setVisible(true);
        });

    }

    private void KoneksiDatabase() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException cnf) {
            System.err.println(cnf.getMessage());
        }
        try {
            koneksi = DriverManager.getConnection("jdbc:mysql://localhost/loketonline", "root", "");
            System.out.println("Koneksi Database Berhasil");
        } catch (SQLException se) {
            System.out.println("Koneksi Database Gagal : " + se);
        } catch (Exception e) {

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmb_pembayaran;
    private javax.swing.JComboBox<String> cmb_pembelian;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton no_paket;
    private javax.swing.JRadioButton paket_1;
    private javax.swing.JRadioButton paket_2;
    private javax.swing.JTextField t_harga;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_pajak;
    private javax.swing.JTextField t_pembeli;
    private javax.swing.JTextField t_total;
    // End of variables declaration//GEN-END:variables
}
